apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-tracker
  labels:
    kraken: 'true'
spec:
  replicas: {{ .Values.tracker.replicas }}
  selector:
    matchLabels:
      kraken-app: tracker
  template:
    metadata:
      labels:
        kraken: 'true'
        kraken-app: tracker
    spec:
      containers:
      - name: redis
        image: redis:5.0
      - name: main
        image: gcr.io/uber-container-tools/kraken-tracker:{{ .Values.kraken.tag }}
        command:
        - /bin/bash
        - -c
        - "sleep 30 && /usr/bin/kraken-tracker --config=/etc/config/tracker.yaml --port=80"
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: kraken
---
kind: Service
apiVersion: v1
metadata:
  name: kraken-tracker
  labels:
    kraken: 'true'
spec:
  clusterIP: None
  selector:
    kraken-app: tracker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
